{"uuid": "457b58bb-67cb-4434-9e02-50c4868a4362", "children": ["6b8ec571-d291-4b68-a0aa-21e08f81d07d"], "befores": [{"name": "setup_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=131.0.6778.109)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6EE906CF5+28821]\n\t(No symbol) [0x00007FF6EE873880]\n\t(No symbol) [0x00007FF6EE71578A]\n\t(No symbol) [0x00007FF6EE712E88]\n\t(No symbol) [0x00007FF6EE703BF9]\n\t(No symbol) [0x00007FF6EE70594F]\n\t(No symbol) [0x00007FF6EE703EBF]\n\t(No symbol) [0x00007FF6EE70371B]\n\t(No symbol) [0x00007FF6EE70365A]\n\t(No symbol) [0x00007FF6EE701274]\n\t(No symbol) [0x00007FF6EE701B3C]\n\t(No symbol) [0x00007FF6EE71885A]\n\t(No symbol) [0x00007FF6EE7B01FE]\n\t(No symbol) [0x00007FF6EE78F2FA]\n\t(No symbol) [0x00007FF6EE7AF412]\n\t(No symbol) [0x00007FF6EE78F0A3]\n\t(No symbol) [0x00007FF6EE75A778]\n\t(No symbol) [0x00007FF6EE75B8E1]\n\tGetHandleVerifier [0x00007FF6EEC3FCED+3408013]\n\tGetHandleVerifier [0x00007FF6EEC5745F+3504127]\n\tGetHandleVerifier [0x00007FF6EEC4B63D+3455453]\n\tGetHandleVerifier [0x00007FF6EE9CBDFB+835995]\n\t(No symbol) [0x00007FF6EE87EB9F]\n\t(No symbol) [0x00007FF6EE87A854]\n\t(No symbol) [0x00007FF6EE87A9ED]\n\t(No symbol) [0x00007FF6EE86A1D9]\n\tBaseThreadInitThunk [0x00007FFE9BA0259D+29]\n\tRtlUserThreadStart [0x00007FFE9CF4AF38+40]\n\n", "trace": "  File \"C:\\Users\\Jubilee\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Jubilee\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Jubilee\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Jubilee\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Jubilee\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Jubilee\\Desktop\\Credence\\CredencePython\\pythonProject\\pythonProject\\Credbank\\testCases\\conftest.py\", line 27, in setup_login\n    driver.get(url_login)\n  File \"C:\\Users\\Jubilee\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 363, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Jubilee\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Jubilee\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1733557128611, "stop": 1733557188262}], "start": 1733557128611, "stop": 1733557188535}